CREATE SEQUENCE IF NOT EXISTS users_sq MINVALUE 1 START WITH 1;
CREATE TABLE IF NOT EXISTS users (
   id INTEGER NOT NULL DEFAULT nextval('users_sq'),
   user_name VARCHAR(200) NOT NULL UNIQUE,
   password VARCHAR(200) NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY(id)
);
