CREATE SEQUENCE IF NOT EXISTS item_sq MINVALUE 1 START WITH 1;
CREATE TABLE IF NOT EXISTS item (
id INTEGER NOT NULL DEFAULT nextval('item_sq'),
description TEXT NOT NULL,
created TIMESTAMP DEFAULT now(),
done BOOLEAN NOT NULL DEFAULT FALSE,
user_id INTEGER NOT NULL,
CONSTRAINT pk_item PRIMARY KEY(id),
CONSTRAINT fk_item_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);